### PR TITLE
Annotated text package and the base classes

### PR DESCRIPTION
**Pull request by Kakarot-SSJ4**

### CODE REVIEW

**Comment by Kakarot-SSJ4** [comment]
@panacekcz

**Comment by Kakarot-SSJ4** [comment]
@panacekcz annotated with `@PolyAll` in ObjectUtils.java

**Review by panacekcz — APPROVED** [review]
Looks ok

**Comment by Kakarot-SSJ4** [comment]
@kelloggm @panacekcz The build has succeeded.

**Pull request merged**
